server:
  port: 9093

spring:
  datasource:
    username: saleem8396
    url: jdbc:mysql://localhost:3306/saleem8396_payementService
    driverClassName: com.mysql.cj.jdbc.Driver
    password: saleem8396@098
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:http://localhost:9292

