

server:
  port: 9092

spring:
  datasource:
    username: saleem8396
    url: jdbc:mysql://localhost:3306/saleem8396_orderService
    driverClassName: com.mysql.cj.jdbc.Driver
    password: saleem8396@098
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://localhost:9292

#eureka:
#  instance:
#    prefer-id-address: true
#  client:
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka